
//import "isomorphic-fetch";
export const FETCH_WEATHER = "COMMAND/FETCH_WEATHER_FOR_LAT_LNG";
export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const WEATHER_ID_RECEIVED = "EVENT/WEATHER_ID_RECEIVED";


export const REQUEST_DRONEDATA_SAGAS = "REQUEST_DRONEDATA_SAGAS"
export const REQUEST_DRONEDATA_SAGAS_RECEIVED = "REQUEST_DRONEDATA_SAGAS_RECEIVED"



